### ISSUE TITLE
Does not build today - return from unknown block

### ISSUE THREAD

**Issue by quicklisp** [orthecreedence/blackbird#14]
http://report.quicklisp.org/2015-01-07/failure-report/blackbird.html has the log. I get this:

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/blackbird/3bebe4cd4434384ba02ffd4bd0ba9ebb0a3fda70/blackbird-20150106-git/promise.lisp
    ; in: DEFUN DO-CATCH
    ;     (RETURN-FROM BLACKBIRD-BASE:CATCHER
    ;       (BLACKBIRD-BASE::REJECT BLACKBIRD-BASE::E))
    ; 
    ; caught ERROR:
    ;   return for unknown block: CATCHER

**Comment by orthecreedence** [comment]
Thanks for reporting, I'm able to reproduce. Checking.

**Comment by orthecreedence** [comment]
Ok, should be fixed!
